
class_list_title = [
    'title',
    'ArticleHeader_headline_2zdFM',
    'articleheader',
    'article-header',
    'article-title',
    'ArticleHeader__hed___GPB7e',
    'article__headline',
    'entry-title',
    'entry-title single-title',
    'col-lg-9 col-md-8',
    'content__headline',
    'name post-title entry-title',
    'articleTitle',
    'artTitle',
    'blog-title',
    'b-item__title',
    'postarea',
    'full-page-article left-col',
    'headline',
    'post_title',
    'post-title',
    'post-title entry-title',
    'post-headline',
    'pg-headline',
    'page-header',
    'content-header ',
    'field-subhead',
    '_8UFs4BVE',
    'the-title',
    'single-title',
    'single-entry-title',
    'story-title',
    'story-body__h1',
    'xxlarge',
    'row',
    'lede-text-only__hed',
    'asset-headline speakable-headline'
] 

class_list_paragraph = [
    'ArticleBody__articleBody___1GSGP',
    'art-postcontent',
    'articles2',
    'article-inner',
    'article-text',                    
    'article-content',
    'article-copy',
    'article_body',
    'article section',
    'articleContentData',
    'article',
    'ArticleBody_body_2ECha',
    'b-item__description',
    'blog-content clearfix',
    'blog-content',
    'body-copy',
    'content-main',
    'content-text', 
    'cb-entry-content clearfix',
    'content__article-body from-content-api js-article__body',
    'content',
    'entry-content clearfix',
    'entry-content full-content',
    'entry clearfix',        
    'entry-content', 
    'entry_content',
    'entry-content print-only',
    'entry-body',
    'entry',                                       
    'entry entry-content',
    'event-text',
    'entry-meta',
    'entry-content-text',
    'field-item even',
    'field-items',
    'field-body',
    'infopage-news',
    'inner-post-entry',
    'td-post-content', 
    'the-content cf',
    'thecontent',
    'text-wrapper',
    'td-post-content td-pb-padding-side',
    'ntText',  
    'new_block',
    'post-single',                     
    'post-content entry-content cf',   
    'post-body entry-content',        
    'post_entry',
    'post_content',
    'post-body',
    'post-content clearfix', 
    'post-bodycopy clearfix',
    'post-single-content box mark-links',
    'post-content',
    'post-9141 post type-post status-publish format-standard has-post-thumbnail hentry category-world tag-fake-news tag-featured tag-satire',
    'vw-post-content clearfix',
    'wpb_wrapper',
    'single-box clearfix entry-content',
    'story-body story-body-1',
    'story-content',
    'story-body__inner',
    'sqs-block-content',
    'single single-post postid-193191 single-format-standard',
    'left relative',
    'l-container',
    'metadata__byline__author',
    'mainContent',
    'mk-single-content clearfix',
    'mvp-post-content-in',
    'group-container ',
    'group-container last',
    'el__leafmedia el__leafmedia--sourced-paragraph',
    'asset-double-wide double-wide p402_premium'
]

class_list_author = [
    'postmetadata',
    'author-article-link',
    'author-section',
    'ArticleHeader_byline_1VRIx',
    'article__author-name',
    'field-author',
    'field-items',
    'fn',
    'name',
    'url fn n',
    'author vcard',
    'author left-edge',
    'author has-bio',
    'author',
    'artAuthor',
    'post-author',
    'post_author',
    'meta pf-author',
    'meta-author',
    'meta-holder',
    'mk-author-name',
    'author-name vcard fn',
    'text font-accent color-brand size-1x-small _1HynphR0',
    'theauthor',
    'byline-author',
    'byline__name',
    'byline',
    'blog-author',
    'createdby',
    'cb-author',
    'username',
    'single-author',
    'small',
    'entry-author-name',
    'metadata__byline__author',
    'asset-metabar-author asset-metabar-item',
    'td-post-author-name'
]


class_list_date = [
    'timestamp',
    'entry-date published',
    'entry-date published updated',
    'content-published-mobile',
    'entry-date',
    'entry-meta',
    'entry-meta-content',
    'entry-meta-date updated',
    'byline byline-left ',
    'bydate',
    'blog-date',
    'b-item__asked-by-time',
    'pub_date',
    'post-date',
    'post_date',
    'post-date updated',               
    'time',
    'published', 
    'article-details',
    'article-timestamp',
    'art-postheadericons art-metadata-icons',
    'article_date',
    'ArticleHeader_date_V9eGk',
    'ArticleTimestamp__timestamp___1klks',
    'artData',
    'cb-date',
    'field-post-date',
    'fa fa-clock-o',
    'update-time',
    'row text font-accent size-1x-small color-darker-gray',
    'dateline',
    'datestamp',
    'date',
    'dt-published date-callout',
    'content__dateline-lm js-lm u-h',
    'grDate',
    'submitted',
    'single-date',
    'mk-publish-date',
    'relative ',
    'asset-metabar-time asset-metabar-item nobyline',
    'article__updated',
    'date no-author',
]
